server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: zippy-backend
  datasource:
    url: jdbc:mysql://localhost:3306/zippy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: ZippyHikariCP
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    open-in-view: false
  mail:
    host: smtp.phamanh.io.vn
    port: 465
    username: zippy@phamanh.io.vn
    password: TiinJzRyX4Aqr0
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 900000
      refresh-token:
        expiration: 604800000
mqtt:
    broker: tcp://36.50.135.207:1883
    client-id: mqtt-listener-service
    username: admin
    password: 123@123
    inboundTopics:
      - robot/+/location
      - robot/+/battery
      - robot/+/status
      - robot/+/container
      - robot/+/trip
      - robot/+/qr-code
      - robot/+/force_move
      - robot/+/warning
    outboundTopics:
      - robot/+/location
      - robot/+/battery
      - robot/+/status
      - robot/+/container
      - robot/+/trip
      - robot/+/qr-code
      - robot/+/force_move
      - robot/+/warning
    qos: 1

payos:
  client-id: f593e1fc-a176-4253-bff0-becea0fe497f
  api-key: d0330c25-c5d5-43ff-b4a8-df1c6d0d04f2
  checksum-key: 4998051de342cd0e2f5fee3d4b0ab103e2ae8b24b7a271b045d980bc224dd81c
  base-url: https://api-merchant.payos.vn

app:
  load-dummy-data: true
