server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: zippy-backend
  datasource:
    url: jdbc:mysql://localhost:3306/zippy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: ZippyHikariCP
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    open-in-view: false
  mail:
    host: smtp.phamanh.io.vn
    port: 465
    username: zippy@phamanh.io.vn
    password: TiinJzRyX4Aqr0
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 900000
      refresh-token:
        expiration: 604800000
mqtt:
    broker: tcp://localhost:1883
    client-id: mqtt-listener-service
    username: khanhnc
    password: 12345678
    inboundTopics:
      - robot/+/location
      - robot/+/battery
      - robot/+/status
      - robot/+/container/+/status
      - robot/+/trip/+
    outboundTopics:
      - robot/+/command/move
      - robot/+/command/request-status
      - robot/+/container/+/command/trip/+/load
      - robot/+/container/+/command/trip/+/pickup
      - robot/+/command/trip/+/move
      - robot/+/command/trip/+/continue
      - robot/+/command/qr-code
    qos: 1

payos:
  client-id: 3ffbee14-99b5-4f3d-b3b1-8bbae79e2bbb
  api_key: e374d39a-92bb-44f6-b0ad-341c76eefcb1
  checksum-key: 5a7917b6ef2febca81e2eabcfce362bf70a6880d66aa76be0ee69f761cd836fb
  base-url: https://api-merchant.payos.vn

app:
  load-dummy-data: true
